[package]
name = "treedb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
blake3 = { version = "1.6.1", features = ["mmap", "rayon"] }
reflink-copy = "0.1.25"
rusqlite = "0.34.0"

[dev-dependencies]
tempfile = "3.17.1"
